### PR TITLE
[PLAT-5467] fix(react-native): Ensure unhandled promise rejections are logged out

### LINKED ISSUE #1135: React-native: Async function swallowing console error
### Describe the bug
When an exception occurs in a component function with the async keyword in the signature, the error is not being logged to the console.

### Steps to reproduce
1. Pull down this repo's master branch and run (linked below).  This is a clone of the rn063example folder with the changes in App.js to reproduce what I am experiencing.
2. When the app is running, click the red text button.
3. Doing this is when I did not see the console error.

### Environment
* Bugsnag version: 7.3.0-alpha.12 (originally experienced on 7.5.2)
* Browser framework version (if any):
    * React: 0.63.0 (originally experienced on 0.63.2)
* Device (e.g. iphonex): iPhone 11 (13.2.2) and Pixel 3 XL (API 29)

### Example Repo 

https://github.com/ShawnCholeva/bugsnag-async-func-error

### Example code snippet 

Screen Shot 2020-11-18 at 3 01 24 PM

<details><summary>Error messages:</summary>
Screen Shot 2020-11-18 at 3 01 37 PM

```

```
</details>

### PR DESCRIPTION
**Pull request by bengourley**
## Goal

When adding the `onUnhandled` event to the rejection tracker, it inadvertantly prevents the "possibly unhandled rejection" warning from displaying.

Fixes #1135.

## Design

Unfortunately there was no way to import or reference the original function, so it needed to be copied into this repo. The risk here is that it gets out of date with the original.

## Changeset

Added warning log that only gets printed in dev (as per the default).

## Testing

Unit tests were updated and manual tests were run.

### CODE REVIEW

File: packages/plugin-react-native-unhandled-rejection/rejection-handler.js [hunk 1]
```diff
@@ -16,8 +18,20 @@ module.exports = {
...
         client._notify(event)
+        // adding our own onUnhandled callback means the default log message doesn't happen, so make it happen here
+        if (typeof __DEV__ !== 'undefined' && __DEV__) logError(id, error)
       }
     })
     return () => rnPromise.disable()
   }
 }
+
+// this function is copied in from the promise module, since it's not exported and we can't reference it:
```
Comment (imjoehaines) [inline packages/plugin-react-native-unhandled-rejection/rejection-handler.js:29]: Not sure if we need to add the license here too; I guess this isn't a "substantial portion" so maybe not?

**Review by imjoehaines — APPROVED** [review]

File: packages/plugin-react-native-unhandled-rejection/rejection-handler.js (hunk 1 above)
Comment (bengourley) [reply packages/plugin-react-native-unhandled-rejection/rejection-handler.js:29]: It doesn't seem that substantial to me but IANAL 🤷
