### PR TITLE
fix(plugin-koa): Ensure unhandled Koa errors are logged out

### LINKED ISSUE #602: Bugsnag swallows error logging in node/koa
Hi, 

When using bugsnag with Koa, bugsnag swallows the error log in the console. This is particularly unhelpful in local development where I don't want the errors sent to bugsnag but I do want to see them in my console. I'd also still like to see the errors in my production environment logging.

I have a repro here https://github.com/keattang/bugsnag-bug-repro

This is a bug that I reported in the previous, non-universal, version of the bugsnag node client. It was fixed then but appears to have come back.

### PR DESCRIPTION
**Pull request by bengourley**
Our plugin adds an `"onerror"` handler to the Koa app, which [stops the default from being called](https://github.com/koajs/koa/blob/a245d18a131341feec4f87659746954e78cae780/lib/application.js#L129).

The default error handler which prints the error is available at `ctx.app.onerror` so by calling through to that after notifying, it exhibits the default behaviour.

Tested manually with `notifyReleaseStages` both allowing and preventing delivery and added a unit test to ensure the original handler is called.

__Output before:__

```
[bugsnag] Report not sent due to releaseStage/notifyReleaseStages configuration
```

__Output after:__

```
[bugsnag] Report not sent due to releaseStage/notifyReleaseStages configuration

  Error: Invalid DSL syntax
      at /Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/app.js:29:29
      at dispatch (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-compose/index.js:42:32)
      at requestHandler (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/dist/bugsnag-koa.js:778:15)
      at dispatch (/Users/bengourley/Development/bugsnag-js/packages/plugin-koa/scratch/node_modules/koa-compose/index.js:42:32)
```

Fixes #602

### CODE REVIEW

File: packages/plugin-koa/src/koa.js [hunk 1]
```diff
@@ -33,7 +33,13 @@ module.exports = {
           ctx.bugsnag.notify(createReportFromErr(err, handledState))
         }
         if (!ctx.response.headerSent) ctx.response.status = err.status || 500
-        ctx.app.onerror(err)
+        try {
+          // this function will throw if you give it a non-error, but we still want
+          // to output that, so if it throws, pass it back what it threw (a TypeError)
+          ctx.app.onerror(err)
+        } catch (e) {
```
Comment (bengourley) [inline packages/plugin-koa/src/koa.js]: https://github.com/koajs/koa/blob/a245d18a131341feec4f87659746954e78cae780/lib/application.js#L183
